# Generated by Django 4.2.11 on 2024-05-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roastery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
