# Generated by Django 4.2.11 on 2024-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roastery', '0005_rename_coffee_variant_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='coffee_size',
            old_name='description',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='coffee_size',
            name='name',
        ),
        migrations.AddField(
            model_name='coffee_size',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
