# Generated by Django 4.2.11 on 2024-05-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roastery', '0006_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Coffee_Variant',
        ),
    ]
