# Generated by Django 4.2.11 on 2024-05-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roastery', '0007_remove_product_variant_delete_coffee_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grind_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Grind', to='roastery.coffee_grind'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Origin', to='roastery.coffee_origin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Size', to='roastery.coffee_size'),
        ),
    ]
