# Generated by Django 4.2.11 on 2024-05-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roastery', '0009_coffeesize_rename_coffee_grind_coffeegrind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeesize',
            name='size',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='roastery.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='grind_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='roastery.coffeegrind'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='roastery.coffeeorigin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='roastery.coffeesize'),
        ),
    ]
