# Generated by Django 4.2.11 on 2024-05-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roastery', '0011_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeorigin',
            name='continent',
            field=models.IntegerField(choices=[(0, 'African'), (1, 'Asian'), (2, 'American')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
