# Generated by Django 3.2.25 on 2024-09-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roastery', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound Sterling'), ('JPY', 'JPY - Japanese Yen'), ('AUD', 'AUD - Australian Dollar'), ('CAD', 'CAD - Canadian Dollar'), ('CHF', 'CHF - Swiss Franc'), ('CNY', 'CNY - Chinese Yuan'), ('SEK', 'SEK - Swedish Krona'), ('NZD', 'NZD - New Zealand Dollar'), ('MXN', 'MXN - Mexican Peso'), ('SGD', 'SGD - Singapore Dollar'), ('HKD', 'HKD - Hong Kong Dollar'), ('NOK', 'NOK - Norwegian Krone'), ('KRW', 'KRW - South Korean Won'), ('TRY', 'TRY - Turkish Lira'), ('INR', 'INR - Indian Rupee'), ('RUB', 'RUB - Russian Ruble'), ('ZAR', 'ZAR - South African Rand'), ('BRL', 'BRL - Brazilian Real'), ('ILS', 'ILS - Israeli New Shekel'), ('PLN', 'PLN - Polish Zloty'), ('THB', 'THB - Thai Baht'), ('DKK', 'DKK - Danish Krone'), ('HUF', 'HUF - Hungarian Forint'), ('CZK', 'CZK - Czech Koruna'), ('CLP', 'CLP - Chilean Peso'), ('COP', 'COP - Colombian Peso'), ('PEN', 'PEN - Peruvian Sol'), ('ARS', 'ARS - Argentine Peso'), ('MYR', 'MYR - Malaysian Ringgit'), ('PHP', 'PHP - Philippine Peso'), ('PKR', 'PKR - Pakistani Rupee'), ('MAD', 'MAD - Moroccan Dirham'), ('AED', 'AED - United Arab Emirates Dirham'), ('BHD', 'BHD - Bahraini Dinar'), ('KWD', 'KWD - Kuwaiti Dinar'), ('OMR', 'OMR - Omani Rial'), ('JOD', 'JOD - Jordanian Dinar'), ('DZD', 'DZD - Algerian Dinar'), ('TND', 'TND - Tunisian Dinar')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
