# Generated by Django 3.2.25 on 2024-09-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roastery', '0015_auto_20240915_2059'),
        ('roastery', '0015_auto_20240916_1939'),
    ]

    operations = [
    ]
