# Generated by Django 3.2.25 on 2024-09-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roastery', '0015_auto_20240923_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='grind_id',
            new_name='grind',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='origin_id',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_id',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
